
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jphigzilwqdmnsnrfqsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwaGlnemlsd3FkbW5zbnJmcXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0OTQ4MzMsImV4cCI6MjA1NTA3MDgzM30.XCmjMqOfApCUREaK8A1cP4u20ef8sU98gCEijtqdw3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
